services:
  webserver:
    build:
      context: .
      dockerfile: ./dockerfile-server
      args:
        # Secret vars
        SECRET_KEY: ${SECRET_KEY}
        # Common
        NODE_ENV: 'production'
        FRONTEND_HOST: ${FRONTEND_HOST}
        BACKEND_HOST: ${BACKEND_HOST}
        FRONTEND_PORT: ${FRONTEND_PORT}
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      # Secret vars
      SECRET_KEY: ${SECRET_KEY}
      # Common
      NODE_ENV: 'production'
      FRONTEND_HOST: ${FRONTEND_HOST}
      BACKEND_HOST: ${BACKEND_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}


  client:
    build:
      context: .
      dockerfile: ./dockerfile-client
      args:
        # Common vars
        NODE_ENV: 'production'
        FRONTEND_HOST: ${FRONTEND_HOST}
        BACKEND_HOST: ${BACKEND_HOST}
        FRONTEND_PORT: ${FRONTEND_PORT}
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      # Common vars
      NODE_ENV: 'production'
      FRONTEND_HOST: ${FRONTEND_HOST}
      BACKEND_HOST: ${BACKEND_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}

