services:
  webserver:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - FRONTEND_URL=http://client:5173
      - BACKEND_URL=http://webserver:3001
      - BACKEND_WS_URL=ws://webserver:3001
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./server/shared:/app/shared
      - ./.env:/.env
    environment:
      - FRONTEND_URL=http://client:5173
      - BACKEND_URL=http://webserver:3001
      - BACKEND_WS_URL=ws://webserver:3001
