export const messageTypes = {
  CHAT_UPDATE: 'CHAT_UPDATE',
  PLAYER_MOVE: 'PLAYER_MOVE',
  GAME_UPDATE: 'GAME_UPDATE',
  CONNECTED: 'CONNECTED',
  CONNECTIONS_UPDATE: 'CONNECTIONS_UPDATE'
} as const;

export const BOARD_SIZE = 13;